TAM.EFaktur.Web/Models/Master_MenuRole/Master_MenuRoleCreateUpdate.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TAM.EFaktur.Web.Models.Master_MenuRole
{
    public class Master_MenuRoleCreateUpdate
    {
        public Guid Id { set; get; }
        public string RoleId { set; get; }
        public string MenuId { set; get; }
        public string RoleCode { set; get; }
        public string MenuCode { set; get; }
        public string ButtonName { set; get; }
        public DateTime EvenDate { get; set; }
        public string EvenActor { get; set; }
    }
}

TAM.EFaktur.Web/Models/Master_MenuRole/MenuRole.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TAM.EFaktur.Web.Models.Master_MenuRole
{
    public class MenuRole : BaseModel
    {
        public System.Guid RoleId { get; set; }
        public System.Guid MenuId { get; set; }
        public string ButtonName { get; set; }

    }
}

TAM.EFaktur.Web/Models/Master_MenuRole/MenuRoleCreateUpdate.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TAM.EFaktur.Web.Models.Master_MenuRole
{
    public class MenuRoleCreateUpdate
    {
        public Guid Id { get; set; }
        public string RoleId { get; set; }
        public string MenuId { get; set; }
        public string ButtonName { get; set; }
        public string CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string RowStatus { get; set; }
    }
}

TAM.EFaktur.Web/Models/Master_MenuRole/MenuRoleDashboardSearchParamViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TAM.EFaktur.Web.Models.Master_MenuRole
{
    public class MenuRoleDashboardSearchParamViewModel
    {
        public string RoleCode { get; set; } 
        public string MenuCode { get; set; }
        public string MenuName { get; set; }
        public string ButtonName { get; set; }
        
    }
}

TAM.EFaktur.Web/Models/Master_MenuRole/MenuRoleDashboardViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TAM.EFaktur.Web.Models.Master_MenuRole
{
    public class MenuRoleDashboardViewModel
    {
        public int RowNum { get; set; }
        public Guid Id { get; set; }
        public string RoleCode { get; set; }
        public string MenuCode { get; set; }
        public string MenuName { get; set; }
        public string ButtonName { get; set; }
        
    }
}

TAM.EFaktur.Web/Models/Master_MenuRole/MenuRoleRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TAM.EFaktur.Web.Models.Master_MenuRole
{
    public class MenuRoleRepository : BaseRepository
    {

        #region Singleton
        private MenuRoleRepository() { }
        private static MenuRoleRepository instance = null;
        public static MenuRoleRepository Instance
        {
            get
            {
                if (instance == null)
                {
                    instance = new MenuRoleRepository();
                }
                return instance;
            }
        }
        #endregion

        #region Counter Data
        public int Count(MenuRoleDashboardSearchParamViewModel model)
        {
            dynamic args = new
            {
                RoleCode = model.RoleCode,
                MenuCode = model.MenuCode,
                MenuName = model.MenuName
            };

            return db.SingleOrDefault<int>("Master_MenuRole/usp_CountMenuRoleListDashboard", args);
        }
        #endregion

        #region Processing Data
        public List<MenuRoleDashboardViewModel> GetList(MenuRoleDashboardSearchParamViewModel model, int SortBy, string SortDirection, int FromNumber, int ToNumber)
        {
            dynamic args = new
            {
                RoleCode = model.RoleCode,
                MenuCode = model.MenuCode,
                MenuName = model.MenuName,
                ButtonName = model.ButtonName,
                SortBy = SortBy,
                SortDirection = SortDirection,
                FromNumber = FromNumber,
                ToNumber = ToNumber
            };
            IEnumerable<MenuRoleDashboardViewModel> result = db.Query<MenuRoleDashboardViewModel>("Master_MenuRole/usp_GetRoleMenuListDashboard", args);
            return result.ToList();
        }

        public MenuRole GetById(Guid Id)
        {
            return db.SingleOrDefault<MenuRole>("Master_MenuRole/usp_GetRoleMenuByID", new { Id = Id });
        }


        #endregion

        public List<DropdownViewModel> GetMenuDropdown()
        {

            IEnumerable<DropdownViewModel> result = db.Query<DropdownViewModel>("Master_MenuRole/usp_DropDownMenu");
            return result.ToList();
        }


        //insert Data
        public Result Insert(Master_MenuRoleCreateUpdate model, string EventActor, DateTime EventDate)
        {
            try
            {
                dynamic args = new
                {
                    Id = Guid.NewGuid(),
                    RoleId = model.RoleId,
                    MenuId = model.MenuId,
                    ButtonName = model.ButtonName,
                    EventDate = EventDate.FormatSQLDate(),
                    EventActor = EventActor
                };
                db.Execute("Master_MenuRole/usp_Insert_TB_M_RoleMenu", args);
                return MsgResultSuccessInsert();
            }
            catch (Exception e)
            {
                return MsgResultError(e.Message.ToString());
            }
        }

        //Update Data
        public Result Update(Master_MenuRoleCreateUpdate model, string EventActor, DateTime EventDate)
        {
            try
            {
                dynamic args = new
                {
                    Id = model.Id,
                    RoleId = model.RoleId,
                    MenuId = model.MenuId,
                    ButtonName = model.ButtonName,
                    EventDate = EventDate.FormatSQLDate(),
                    EventActor = EventActor

                };
                db.Execute("Master_MenuRole/usp_Update_TB_M_RoleMenu", args);
                return MsgResultSuccessUpdate();
            }
            catch (Exception e)
            {
                return MsgResultError(e.Message.ToString());
            }
        }

        //Update Data
        public Result Delete(Master_MenuRoleCreateUpdate model, string EventActor, DateTime EventDate)
        {
            try
            {
                dynamic args = new
                {
                    Id = model.Id,
                    RoleCode = model.RoleCode,
                    Menucode = model.MenuCode,
                    EventDate = EventDate.FormatSQLDate(),
                    EventActor = EventActor

                };
                db.Execute("Master_MenuRole/usp_Delete_TB_M_RoleMenu", args);
                return MsgResultSuccessDelete();
            }
            catch (Exception e)
            {
                return MsgResultError(e.Message.ToString());
            }

        }
    }
}

TAM.EFaktur.Web/Models/Master_MenuRole/MenuRoleUpdate.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TAM.EFaktur.Web.Models.Master_MenuRole
{
    public class MenuRoleUpdate
    {
        public Guid Id { get; set; }
        public string RoleId { get; set; }
        public string MenuId { get; set; }
        public string ButtonName { get; set; }
        public string ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    }
}

TAM.EFaktur.Web/Controllers/Master_MenuRoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using TAM.EFaktur.Web.Models;
using TAM.EFaktur.Web.Models.Master_MenuRole;
using Toyota.Common.Web.Platform;


namespace TAM.EFaktur.Web.Controllers
{
    public class Master_MenuRoleController : PageController
    {
        //
        // GET: /Master_MenuRole/

        public Master_MenuRoleController()
        {
            Settings.Title = "Maintain-Config";
        }

        public ActionResult PopupCreateMenuRole()
        {
            return PartialView("_PopupCreateMenuRole");
        }

        public ActionResult PopupUpdateMenuRole(Guid Id)
        {

            ViewData["UpdateMenuRole"] = MenuRoleRepository.Instance.GetById(Id);
            return PartialView("_PopupUpdateMenuRole");
        }

        public ActionResult PopupDeleteMenuRole(Guid Id)
        {

            ViewData["DeleteMenuRole"] = MenuRoleRepository.Instance.GetById(Id);
            return PartialView("_PopupDeleteMenuRole");
        }

        public ActionResult PopupMultipleSearch(string Id)
        {
            ViewBag.ElementId = Id;
            return PartialView("_PopupMultipleSearch");
        }
        [HttpPost]
        public ActionResult GetMenuRoleList(FormCollection collection, int sortBy, bool sortDirection, int page, int size)
        {
            var data = collection["data"];
            var model = new MenuRoleDashboardSearchParamViewModel();

            if (!string.IsNullOrEmpty(data))
                model = new JavaScriptSerializer().Deserialize<MenuRoleDashboardSearchParamViewModel>(data);

            Paging pg = new Paging
            (
                MenuRoleRepository.Instance.Count(model),
                page,
                size
            );
            ViewData["Paging"] = pg;
            ViewData["MenuRoleListDashboard"] = MenuRoleRepository.Instance.GetList(model, sortBy, sortDirection ? "ASC" : "DESC", pg.StartData, pg.EndData);

            return PartialView("_SimpleGrid");
        }

        //Insert Data
        [HttpPost]
        public JsonResult Insert(FormCollection collection)
        {
            var data = collection["data"];

            Result result = new Result();
            if (!string.IsNullOrEmpty(data))
            {
                try
                {
                    var model = new JavaScriptSerializer().Deserialize<Master_MenuRoleCreateUpdate>(data);



                    result = MenuRoleRepository.Instance.Insert(model, "Handika Satwika R", DateTime.Now);

                }
                catch (Exception ex)
                {
                    throw ex;
                }
            }
            else
            {
                result.ResultCode = false;
                result.ResultDesc = "Data not found or not valid";
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        //Update Data

        [HttpPost]
        public JsonResult Update(FormCollection collection)
        {
            var data = collection["data"];

            Result result = new Result();
            if (!string.IsNullOrEmpty(data))
            {
                try
                {
                    var model = new JavaScriptSerializer().Deserialize<Master_MenuRoleCreateUpdate>(data);



                    result = MenuRoleRepository.Instance.Update(model, "Handik Satwika R", DateTime.Now);

                }
                catch (Exception ex)
                {
                    throw ex;
                }
            }
            else
            {
                result.ResultCode = false;
                result.ResultDesc = "Data not found or not valid";
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Delete(FormCollection collection)
        {
            var data = collection["data"];

            Result result = new Result();
            if (!string.IsNullOrEmpty(data))
            {
                try
                {
                    var model = new JavaScriptSerializer().Deserialize<Master_MenuRoleCreateUpdate>(data);



                    result = MenuRoleRepository.Instance.Delete(model, "Handik Satwika R", DateTime.Now);

                }
                catch (Exception ex)
                {
                    throw ex;
                }
            }
            else
            {
                result.ResultCode = false;
                result.ResultDesc = "Data not found or not valid";
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetMenuDropdown()
        {


            List<DropdownViewModel> model = new List<DropdownViewModel>();

            model = MenuRoleRepository.Instance.GetMenuDropdown();
            return Json(model, JsonRequestBehavior.AllowGet);
        }
    }
}

TAM.EFaktur.Web/Views/Master_MenuRole/Master_MenuRole.cshtml
@{
    ViewBag.Title = "Maintain Menu Role";
}

@section HeadScript{
    <style>
        ._searchCriteria {
            display: true;
        }
    </style>
}

@Html.Partial("_SearchCriteria")

<div class="_line-br"></div>
<div class="row">
    <div class="col-xs-12 col-sm-6">
        @Html.Partial("_UIPageSize")
    </div>
</div>
@Html.Partial("_SimpleGrid")


@section BodyScript{
    <script type="text/javascript">
        $(document).ready(function () {

            $(".btn-edit").click(function () {
                $("#edit-popup").modal();
            });

            $(".btn-delete").click(function () {
                $("#delete-confirm").modal();
            });



            /* toggle show or hide searching criteria (that has class _searchCriteria) */
            $("#lnsearch-toggle").click(function () {
                var _criteria = $("._searchCriteria");
                _criteria.toggle(200, "linear");

                var text = $("#lnsearch-toggle").text();
                $("#lnsearch-toggle").text(text == "Expand search criteria" ? "Less search criteria" : "Expand search criteria");
            });


            /* toggle column on tablegrid (that <th> has class _toggle-detail) */
            //$("#btnToggleDetail").click(function () {
            //    var _detail = $("._toggle-detail");

            //    _detail.each(function () {
            //        pos = $(this).index();
            //        $(this).toggle();
            //        $("td:nth-child(" + (pos + 1) + ")").toggle();
            //    });
            //});


        });

    </script>

}
@Html.Partial("_Javascript")

TAM.EFaktur.Web/Views/Master_MenuRole/_Javascript.cshtml
<script type="text/javascript">
    var searchParam = {};
    var sort = {
        sortBy: 1,
        sortDirection: true
    };

    //bind event to buttons
    $("#btnSearch").click(function () {
        searchParam = {
            RoleCode: $("#lookupMenuRoleRoleCode").val(),
            MenuCode: $("#lookupMenuRoleMenuCode").val(),
            MenuName: $("#lookupMenuRoleMenuName").val()

        };
        onGet(1);
    });
    $("#ddlPageSize").change(function () {
        onGet(1);
    });

    //fungsi Sort BY
    function sortItem(field) {
        if (sort.sortBy == field) {
            sort.sortDirection = !sort.sortDirection;
        }
        else {
            sort.sortBy = field;
            sort.sortDirection = true;
        }
        onGet(1);
    }

    //Ajax POST/GET Method
    function onGet(page) {
        $.ajax({
            type: "POST",
            url: "@Html.Toyota().Page.GetActionUrl("GetMenuRoleList")",
            data: {
                data: JSON.stringify(searchParam),
                sortBy: sort.sortBy,
                sortDirection: sort.sortDirection,
                page: page,
                size: $("#ddlPageSize").val()
            },
            beforeSend: function () {
                $('#btnSearch').button('loading');
                if (DEBUG) {
                    console.log('Search Start');
                }
            },
            success: function (result) {
                $("#gridMenuRole").html(result);
                if (DEBUG) {
                    console.log('Search Result Rendered');
                }
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                if (DEBUG) {
                    console.log("error: " + errorThrown);
                }
            },
            complete: function () {
                $('#btnSearch').button('reset');
                if (DEBUG) {
                    console.log('Search Done');
                }
            }
        });
    }

    function onCallback(pg) {
        var mx = $("#txtMaxPage").val();
        if ((pg <= mx) && (pg > 0)) {
            onGet(pg);
        }
        else {
            msgWarning('Page not found');
        }
    }

    //GetRoleDropdownList
    var MenuRole = {};
    var URLDropdownRole;
    var URLDropdownMenu;
    var URLSave = "@Html.Toyota().Page.GetActionUrl("Insert")";
    var URLSaveUpdate = "@Html.Toyota().Page.GetActionUrl("Update")";
    var URLSaveDelete = "@Html.Toyota().Page.GetActionUrl("Delete")";
    $(document).ready(function () {
        URLDropdownRole = "@Html.Toyota().Page.BaseUrl" + "/Master_Role/GetRoleDropdown";


        URLDropdownMenu = "@Html.Toyota().Page.BaseUrl" + "/Master_MenuRole/GetMenuDropdown";
    });

</script>

TAM.EFaktur.Web/Views/Master_MenuRole/_PopupCreateMenuRole.cshtml
<div class="modal-body">
    <button type="button" class="close" data-dismiss="modal">
        <span aria-hidden="true">×</span>
        <span class="sr-only">Close</span>
    </button>
    <h4 class="modal-title">Create New Menu-Role</h4>
    <hr />

    <form role="form" class="form-horizontal" id="InputMenuRoleForm">
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6">
                <div class="form-group form-group-xs">
                    <label class="col-xs-12 col-sm-3 col-md-4 control-label text-muted">Role Code</label>
                    <div class="col-xs-12 col-sm-9 col-md-8">
                        <select id="ddlRolePopup" name="RoleCode" class="form-control">
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6">
                <div class="form-group form-group-xs">
                    <label class="col-xs-12 col-sm-3 col-md-4 control-label text-muted">Menu Code</label>
                    <div class="col-xs-12 col-sm-9 col-md-8">
                        <select id="ddlMenuPopup" name="MenuCode" class="form-control">
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6">
                <div class="form-group form-group-xs">
                    <label class="col-xs-12 col-sm-3 col-md-4 control-label text-muted">Button Name</label>
                    <div class="col-xs-12 col-sm-9 col-md-8">
                        <input id="txtButtonName" name="ButtonName" type="text" class="form-control" />
                    </div>
                </div>
            </div>
        </div>

        <div class="row">

            <div class="col-xs-12 text-right">
                <div class="btn-group-sm">
                    <button type="submit" class="btn btn-primary" id="btnSave">Save</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal" id="btnCancel">Cancel</button>
                </div>
            </div>
        </div>
    </form>
</div>

<script type="text/javascript">

    getDropdownData(URLDropdownRole, "ddlRolePopup");
    getDropdownData(URLDropdownMenu, "ddlMenuPopup");

   
    $(document).ready(function () {
        $('#InputMenuRoleForm').bootstrapValidator({
            live: 'enabled',
            fields: {
                RoleCode: {
                    validators: {
                        notEmpty: {
                            message: 'Role Code is required and can\'t be empty'
                        }
                    }
                },
                MenuCode: {
                    validators: {
                        notEmpty: {
                            message: 'Menu Code is required and can\'t be empty'
                        }
                    }
                },
                ButtonName: {
                    validators: {
                        notEmpty: {
                            message: 'Button Name is required and can\'t be empty'
                        }
                    }
                }

            }
        })
        .on('success.form.bv', function (e) {
            // Prevent form submission
            e.preventDefault();

            onSubmit();
        });
    });


    //Ajax POST/GET Method

    function onSubmit() {
        MenuRole = {
            RoleId: $("#ddlRolePopup").val(),
            MenuId: $("#ddlMenuPopup").val(),
            ButtonName: $("#txtButtonName").val(),
        };
        $.ajax({
            type: "POST",
            url: URLSave,
            data: {
                data: JSON.stringify(MenuRole)
            },
            beforeSend: function () {
                $('#btnSave').button('loading');
                if (DEBUG) {
                    console.log('Save Start');
                }
            },
            success: function (result) {
                if (result.ResultCode) {
                    msgOk(result.ResultDesc);
                    onGet(1);
                    $('#btnCancel').click();
                }
                else {
                    msgError(result.ResultDesc);
                }
                if (DEBUG) {
                    console.log('Save Success');
                }
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                if (DEBUG) {
                    console.log("error: " + errorThrown);
                }
                msgError("An error has occured");
            },
            complete: function () {
                $('#btnSave').button('reset');
                if (DEBUG) {
                    console.log('Save Done');
                }
              
            }
        });
    }

</script>

TAM.EFaktur.Web/Views/Master_MenuRole/_SearchCriteria.cshtml
<form role="form" class="form-horizontal" id="searchForm">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6 _searchCriteria">
            <div class="form-group form-group-xs">
                <label class="col-xs-12 col-sm-3 col-md-4 control-label text-muted">Role Code</label>
                <div class="col-xs-12 col-sm-9 col-md-8">
                    <div class="input-group input-group input-group-xs">
                        <input id="txtMenuRoleRoleCode" type="text" class="form-control" readonly />
                        <input id="lookupMenuRoleRoleCode" type="hidden" />
                        <span class="input-group-btn">
                            <a class="btn btn-primary modal-link" href="@Url.Action("PopupMultipleSearch", "Master_MenuRole", new { Id = "lookupMenuRoleRoleCode" })"><i class="fa fa-search"></i></a>
                        </span>
                    </div>
                </div>
            </div>
            <div class="form-group form-group-xs _searchCriteria">
                <label class="col-xs-12 col-sm-3 col-md-4 control-label text-muted">Menu Code</label>
                <div class="col-xs-12 col-sm-9 col-md-8">
                    <div class="input-group input-group input-group-xs">
                        <input id="txtMenuRoleMenuCode" type="text" class="form-control" readonly />
                        <input id="lookupMenuRoleMenuCode" type="hidden" />
                        <span class="input-group-btn">
                            <a class="btn btn-primary modal-link" href="@Url.Action("PopupMultipleSearch", "Master_MenuRole", new { Id = "lookupMenuRoleMenuCode" })"><i class="fa fa-search"></i></a>
                        </span>
                    </div>

                </div>
            </div>

        </div>


        <div class="col-xs-12 col-sm-6 col-md-6 _searchCriteria">

            <div class="form-group form-group-xs _searchCriteria">
                <label class="col-xs-12 col-sm-3 col-md-4 control-label text-muted">Menu Name</label>
                <div class="col-xs-12 col-sm-9 col-md-8">
                    <div class="input-group input-group input-group-xs">
                        <input id="txtMenuRoleMenuName" type="text" class="form-control" readonly />
                        <input id="lookupMenuRoleMenuName" type="hidden" />
                        <span class="input-group-btn">
                            <a class="btn btn-primary modal-link" href="@Url.Action("PopupMultipleSearch", "Master_MenuRole", new { Id = "lookupMenuRoleMenuName" })"><i class="fa fa-search"></i></a>
                        </span>
                    </div>
                </div>
            </div>

        </div>

    </div>

    <div class="row">
        <div class="col-xs-6" style="margin-top: 5px;">

        </div>
        <div class="col-xs-6 text-right">
            <div class="btn-group-sm">
                @Html.ActionLink("New Menu Role", "PopupCreateMenuRole", "Master_MenuRole", null, new { @class = "modal-link btn btn-danger" })
                <button type="button" class="btn btn-primary" id="btnSearch" data-loading-text="&lt;i class='fa fa-refresh fa-spin'&gt;&lt;/i&gt; Loading...">Search</button>
                <button type="reset" class="btn btn-default" id="btnClearSearch" onclick="clearSearch()">Clear</button>
            </div>
        </div>
    </div>

</form>

<script type="text/javascript">

    //Clear Form Search
    function clearSearch() {
        document.getElementById("txtMenuRoleRoleCode").value = "";
        document.getElementById("lookupMenuRoleRoleCode").value = "";
        document.getElementById("txtMenuRoleMenuCode").value = "";
        document.getElementById("lookupMenuRoleMenuCode").value = "";
        document.getElementById("txtMenuRoleMenuName").value = "";
        document.getElementById("lookupMenuRoleMenuName").value = "";
    }
</script>

TAM.EFaktur.Web/Views/Master_MenuRole/_SimpleGrid.cshtml
@using TAM.EFaktur.Web.Models.Master_MenuRole
@using TAM.EFaktur.Web.Models

@{
    List<MenuRoleDashboardViewModel> MenuRoleList = (List<MenuRoleDashboardViewModel>)ViewData["MenuRoleListDashboard"];
}

<div id="gridMenuRole">
    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th style="width:70px;"></th>
                    <th onclick="sortItem(1)" style="cursor:pointer">Role Code</th>
                    <th onclick="sortItem(2)" style="cursor:pointer">Menu Code</th>
                    <th onclick="sortItem(3)" style="cursor:pointer">Menu Name</th>
                    <th onclick="sortItem(4)" style="cursor:pointer">Button Name</th>
                </tr>
            </thead>
            <tbody>
                @if (MenuRoleList != null && MenuRoleList.Count > 0)
                {
                    foreach (MenuRoleDashboardViewModel MenuRole in MenuRoleList)
                    {
                        <tr>
                            <td class="text-center">
                                <a href="@Url.Action("PopupUpdateMenuRole", "Master_MenuRole", new { Id = @MenuRole.Id })" class="modal-link btn btn-primary btn-xs btn-edit"><i class="fa fa-edit"></i></a>
                                <a href="@Url.Action("PopupDeleteMenuRole", "Master_MenuRole", new { Id = @MenuRole.Id })" class="modal-link btn btn-primary btn-xs btn-danger"><i class="fa fa-trash"></i></a>
                            </td>
                            <td>@MenuRole.RoleCode</td>
                            <td>@MenuRole.MenuCode</td>
                            <td>@MenuRole.MenuName</td>
                            <td>@MenuRole.ButtonName</td>

                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td class="danger" colspan="19"><b class="padding-5">No Record</b></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="row">
        <div class="col-xs-12 bottom-margin-20">
            @Html.Partial("_UIPaging")
        </div>
    </div>
</div>