TAM.EFaktur.Web/Models/Master_Role/MasterRole.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TAM.EFaktur.Web.Models.Master_Role
{
    public class MasterRole : BaseModel
    {
        public string RoleCode { get; set; }
        public string RoleName { get; set; }
        public string ApplicationCode { get; set; }

    }
}

TAM.EFaktur.Web/Models/Master_Role/MasterRoleCreateUpdate.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TAM.EFaktur.Web.Models.Master_Role
{
    public class MasterRoleCreateUpdate
    {
        public Guid Id { get; set; }
        public string RoleCode { get; set; }
        public string RoleName { get; set; }
        public string ApplicationCode { get; set; }
        public DateTime EvenDate { get; set; }
        public string EvenActor { get; set; }
    }
}

TAM.EFaktur.Web/Models/Master_Role/MasterRoleDashboardSearchParamViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TAM.EFaktur.Web.Models.Master_Role
{
    public class MasterRoleDashboardSearchParamViewModel
    {
        public string RoleCode { get; set; }
        public string RoleName { get; set; }
        public string ApplicationCode { get; set; }
       
    }
}

TAM.EFaktur.Web/Models/Master_Role/MasterRoleDashboardViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TAM.EFaktur.Web.Models.Master_Role
{
    public class MasterRoleDashboardViewModel
    {
        public int RowNum { get; set; }
        public Guid Id { get; set; }
        public string RoleCode { get; set; }
        public string RoleName { get; set; }
        public string ApplicationCode { get; set; }

    }
}

TAM.EFaktur.Web/Models/Master_Role/MasterRoleRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TAM.EFaktur.Web.Models.Master_Role
{
    public class MasterRoleRepository : BaseRepository
    {
        #region Singleton
        private MasterRoleRepository() { }
        private static MasterRoleRepository instance = null;
        public static MasterRoleRepository Instance
        {
            get 
            {
                if (instance == null)
                {
                    instance = new MasterRoleRepository();
                }
                return instance;
            }
        }
        #endregion

        #region Counter Data
        public int Count(MasterRoleDashboardSearchParamViewModel model)
        {
            dynamic args = new
            {
                
                RoleCode = model.RoleCode,
                RoleName = model.RoleName,
                ApplicationCode = model.ApplicationCode
                
            };

            return db.SingleOrDefault<int>("Master_Role/usp_CountMasterRoleListDashboard", args);
        }
        #endregion

        #region Processing Data

        public List<MasterRoleDashboardViewModel> GetList(MasterRoleDashboardSearchParamViewModel model, int SortBy, string SortDirection, int FromNumber, int ToNumber)
        ///public List<Role> GetList(string RoleCode, string RoleName)
        {
            dynamic args = new
            {
                RoleCode = model.RoleCode,
                RoleName = model.RoleName,
                ApplicationCode=model.ApplicationCode,
                SortBy = SortBy,
                SortDirection = SortDirection,
                FromNumber = FromNumber,
                ToNumber = ToNumber
               
            };
            IEnumerable<MasterRoleDashboardViewModel> result = db.Query<MasterRoleDashboardViewModel>("Master_Role/usp_GetRoleListDashboard", args);
            //IEnumerable<Role> result = db.Query<Role>("Role/nosqlyet", args);
            return result.ToList();
        }

        public MasterRole GetById(Guid Id)
        {
            return db.SingleOrDefault<MasterRole>("Master_Role/usp_GetRoleById", new { Id = Id });
        }

        //insert Data
        public Result Insert (MasterRoleCreateUpdate model, string EventActor, DateTime EventDate)
        {
            try
            {
                dynamic args = new
                {
                    Id = Guid.NewGuid(),
                    RoleCode = model.RoleCode,
                    RoleName = model.RoleName,
                    ApplicationCode = model.ApplicationCode,
                    EventDate = EventDate.FormatSQLDate(),
                    EventActor = EventActor
                };
                db.Execute("Master_Role/usp_Insert_TB_M_Role", args);
                return MsgResultSuccessInsert();
            }
            catch (Exception e)
            {
                return MsgResultError(e.Message.ToString());
            }
        }
        #endregion

        //Update Data
        public Result Update (MasterRoleCreateUpdate model, string EventActor, DateTime EventDate)
        {
            try
            {
                dynamic args = new
                {
                    Id = model.Id,
                    RoleCode = model.RoleCode,
                    RoleName = model.RoleName,
                    ApplicationCode = model.ApplicationCode,
                    EventDate = EventDate.FormatSQLDate(),
                    EventActor = EventActor,
                    
                };
                db.Execute("Master_Role/usp_UpdateMasterRole", args);
                return MsgResultSuccessUpdate();
            }
            catch (Exception e)
            {
                return MsgResultError(e.Message.ToString());
            }
        }

        //Delete Data
        public Result Delete(MasterRoleCreateUpdate model, string EventActor, DateTime EventDate)
        {
            try
            {
                dynamic args = new
                {
                    Id = model.Id,
                    EventDate = EventDate.FormatSQLDate(),
                    EventActor = EventActor,

                };
                db.Execute("Master_Role/usp_Delete_TB_M_Role", args);
                return MsgResultSuccessDelete();
            }
            catch (Exception e)
            {
                return MsgResultError(e.Message.ToString());
            }
        }

        #region GetDropdown

        public List<DropdownViewModel>GetRoleDropdown() 
        {

            IEnumerable<DropdownViewModel> result = db.Query<DropdownViewModel>("Master_Role/usp_DropDownRole");
            return result.ToList();
        }
    }
        #endregion
        
 }

TAM.EFaktur.Web/Models/Master_Role/MasterRoleUpdate.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TAM.EFaktur.Web.Models.Master_Role
{
    public class MasterRoleUpdate
    {
        public Guid Id { get; set; }
        public string RoleCode { get; set; }
        public string RoleName { get; set; }
        public string ApplicationCode { get; set; }
        public DateTime EvenDate { get; set; }
        public string EvenActor { get; set; }
        
    }
}

TAM.EFaktur.Web/Models/Master_Role/Role.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TAM.EFaktur.Web.Models.Master_Role
{
    public class Role : BaseModel
    {
        public string RoleCode { get; set; }
        public string RoleName { get; set; }

    }
}

TAM.EFaktur.Web/Models/Master_Role/RoleRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TAM.EFaktur.Web.Models.Master_Role
{
    public class RoleRepository : BaseRepository
    {
        #region Singleton
        private RoleRepository() { }
        private static RoleRepository instance = null;
        public static RoleRepository Instance
        {
            get 
            {
                if (instance == null)
                {
                    instance = new RoleRepository();
                }
                return instance;
            }
        }
        #endregion

        #region Counter Data
        public int Count(string RoleCode, string RoleName)
        {
            dynamic args = new
            {
                RoleCode = RoleCode,
                RoleName = RoleName
                
            };

            return db.SingleOrDefault<int>("Role/countApplications", args); 
        }
        #endregion

        #region Processing Data

        public List<Role> GetList(string RoleCode, string RoleName)
        {
            dynamic args = new
            {
                RoleCode = RoleCode,
                RoleName = RoleName
               
            };
            IEnumerable<Role> result = db.Query<Role>("Role/nosqlyet", args);
            return result.ToList();
        }

        public Role GetById(Guid Id)
        {
            return db.SingleOrDefault<Role>("Role/usp_GetRoleByID", new { Id = Id });
        }

        public Result Save(Role objRole, DateTime EventDate, string EventActor)
        {
            try
            {
                dynamic args = new
                {
                    Id= objRole.Id,
                    RoleCode = objRole.RoleCode,
                    RoleName = objRole.RoleName,
                    RowStatus           = objRole.RowStatus,
                    EventDate           = EventDate,
                    EventActor          = EventActor                
                };
                db.Execute("Role/usp_SaveRole", args);
                return MsgResultSuccessInsert();
            }
            catch (Exception e)
            {
                return MsgResultError(e.Message.ToString());
            }
        }

        public Result Delete(Guid Id)
        {
            try
            {
                db.Execute("Role/usp_DeleteRoleByID", new { Id = Id });
                return MsgResultSuccessDelete();
            }
            catch (Exception e)
            {
                return MsgResultError(e.Message.ToString());
            }
        }

        //Role Dropdown list in Maintain User
       public List<DropdownViewModel> GetRoleDropdownList()
        {

            IEnumerable<DropdownViewModel> result = db.Query<DropdownViewModel>("Master_Role/usp_GetRoleList");
            return result.ToList();
        }
        #endregion

    }
}

TAM.EFaktur.Web/Controllers/Master_RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using TAM.EFaktur.Web.Models;
using TAM.EFaktur.Web.Models.Master_Role;
using Toyota.Common.Web.Platform;

namespace TAM.EFaktur.Web.Controllers
{
    public class Master_RoleController : PageController
    {
        //
        // GET: /Master_Role/

        public Master_RoleController()
        {
            Settings.Title = "Maintain-Role";
        }

        public ActionResult PopupCreateRole()
        {
            return PartialView("_PopupCreateRole");
        }
        public ActionResult PopupUpdateRole(Guid Id)
        {

            ViewData["UpdateRole"] = MasterRoleRepository.Instance.GetById(Id);
            return PartialView("_PopupUpdateRole");
        }

        public ActionResult PopupDeleteRole(Guid Id)
        {

            ViewData["DeleteRole"] = MasterRoleRepository.Instance.GetById(Id);
            return PartialView("_PopupDeleteRole");
        }

        public ActionResult PopupMultipleSearch(string Id)
        {
            ViewBag.ElementId = Id;
            return PartialView("_PopupMultipleSearch");
        }

        [HttpPost]
        public ActionResult GetMasterRoleList(FormCollection collection, int sortBy, bool sortDirection, int page, int size)
        {
            var data = collection["data"];
            var model = new MasterRoleDashboardSearchParamViewModel();

            if (!string.IsNullOrEmpty(data))
                model = new JavaScriptSerializer().Deserialize<MasterRoleDashboardSearchParamViewModel>(data);

            Paging pg = new Paging
            (
                MasterRoleRepository.Instance.Count(model),
                page,
                size
            );
            ViewData["Paging"] = pg;
            ViewData["MasterRoleListDashboard"] = MasterRoleRepository.Instance.GetList(model, sortBy, sortDirection ? "ASC" : "DESC", pg.StartData, pg.EndData);

            return PartialView("_SimpleGrid");
        }

        [HttpPost]
        public JsonResult Insert(FormCollection collection)
        {
            var data = collection["data"];

            Result result = new Result();
            if (!string.IsNullOrEmpty(data))
            {
                try
                {
                    var model = new JavaScriptSerializer().Deserialize<MasterRoleCreateUpdate>(data);



                    result = MasterRoleRepository.Instance.Insert(model, "Handika Satwika R", DateTime.Now);

                }
                catch (Exception ex)
                {
                    throw ex;
                }
            }
            else
            {
                result.ResultCode = false;
                result.ResultDesc = "Data not found or not valid";
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Update(FormCollection collection)
        {
            var data = collection["data"];

            Result result = new Result();
            if (!string.IsNullOrEmpty(data))
            {
                try
                {
                    var model = new JavaScriptSerializer().Deserialize<MasterRoleCreateUpdate>(data);



                    result = MasterRoleRepository.Instance.Update(model, "Handik Satwika R", DateTime.Now);

                }
                catch (Exception ex)
                {
                    throw ex;
                }
            }
            else
            {
                result.ResultCode = false;
                result.ResultDesc = "Data not found or not valid";
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        //Delete Tampilan Data
        [HttpPost]
        public JsonResult Delete(FormCollection collection)
        {
            var data = collection["data"];

            Result result = new Result();
            if (!string.IsNullOrEmpty(data))
            {
                try
                {
                    var model = new JavaScriptSerializer().Deserialize<MasterRoleCreateUpdate>(data);



                    result = MasterRoleRepository.Instance.Delete(model, "Handik Satwika R", DateTime.Now);

                }
                catch (Exception ex)
                {
                    throw ex;
                }
            }
            else
            {
                result.ResultCode = false;
                result.ResultDesc = "Data not found or not valid";
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public JsonResult GetRoleDropdown()
        {


            List<DropdownViewModel> model = new List<DropdownViewModel>();

            model = MasterRoleRepository.Instance.GetRoleDropdown();
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetRoleDropdownList()
        {


            List<DropdownViewModel> model = new List<DropdownViewModel>();

            model = RoleRepository.Instance.GetRoleDropdownList();
            return Json(model, JsonRequestBehavior.AllowGet);
        }

    }
}

TAM.EFaktur.Web/Views/Master_Role/Master_Role.cshtml
@{
    ViewBag.Title = "Maintain Role";
}

@section HeadScript{
    <style>
        ._SearchCriteria {
            display: none;
        }
    </style>
}

@Html.Partial("_SearchCriteria")

<div class="_line-br"></div>
<div class="row">
    <div class="col-xs-12 col-sm-6">
        @Html.Partial("_UIPageSize")
    </div>
</div>

@Html.Partial("_SimpleGrid")


@section BodyScript{
    <script type="text/javascript">
        $(document).ready(function () {

            $(".btn-edit").click(function () {
                $("#edit-popup").modal();
            });

            $(".btn-delete").click(function () {
                $("#delete-confirm").modal();
            });



            /* toggle show or hide searching criteria (that has class _searchCriteria) */
            $("#lnsearch-toggle").click(function () {
                var _criteria = $("._searchCriteria");
                _criteria.toggle(200, "linear");

                var text = $("#lnsearch-toggle").text();
                $("#lnsearch-toggle").text(text == "Expand search criteria" ? "Less search criteria" : "Expand search criteria");
            });


            /* toggle column on tablegrid (that <th> has class _toggle-detail) */
            //$("#btnToggleDetail").click(function () {
            //    var _detail = $("._toggle-detail");

            //    _detail.each(function () {
            //        pos = $(this).index();
            //        $(this).toggle();
            //        $("td:nth-child(" + (pos + 1) + ")").toggle();
            //    });
            //});


        });

    </script>
}
@Html.Partial("_Javascript")

TAM.EFaktur.Web/Views/Master_Role/_Javascript.cshtml
<script type="text/javascript">
    var searchParam = {};
    var sort = {
        sortBy: 1,
        sortDirection: true
    };

    //bind event to buttons
    $("#btnSearch").click(function () {
        searchParam = {
            RoleCode: $("#lookupRoleCode").val(),
            RoleName: $("#lookupRoleName").val(),
            ApplicationCode: $("#lookupApplicationCode").val()

        };
        onGet(1);
    });

    $("#ddlPageSize").change(function () {
        onGet(1);
    });

    function sortItem(field) {
        if (sort.sortBy == field) {
            sort.sortDirection = !sort.sortDirection;
        }
        else {
            sort.sortBy = field;
            sort.sortDirection = true;
        }
        onGet(1);
    }


    //Ajax POST/GET Method
    function onGet(page) {
        $.ajax({
            type: "POST",
            url: "@Html.Toyota().Page.GetActionUrl("GetMasterRoleList")",
            data: {
                data: JSON.stringify(searchParam),
                sortBy: sort.sortBy,
                sortDirection:sort.sortDirection,
                page: page,
                size: $("#ddlPageSize").val()
            },
            beforeSend: function () {
                $('#btnSearch').button('loading');
                if (DEBUG) {
                    console.log('Search Start');
                }
            },
            success: function (result) {
                $("#gridMasterRole").html(result);
                if (DEBUG) {
                    console.log('Search Result Rendered');
                }
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                if (DEBUG) {
                    console.log("error: " + errorThrown);
                }
            },
            complete: function () {
                $('#btnSearch').button('reset');
                if (DEBUG) {
                    console.log('Search Done');
                }

            }
        });
    }

    function onCallback(pg) {
        var mx = $("#txtMaxPage").val();
        if ((pg <= mx) && (pg > 0)) {
            onGet(pg);
        }
        else {
            msgWarning('Page not found');
        }
    }

    var Role = {};
    var URLSave = "@Html.Toyota().Page.GetActionUrl("Insert")";
    var URLSaveUpdate = "@Html.Toyota().Page.GetActionUrl("Update")";
    var URLSaveDelete = "@Html.Toyota().Page.GetActionUrl("Delete")";
</script>

TAM.EFaktur.Web/Views/Master_Role/_PopupCreateRole.cshtml
<div class="modal-body">
    <button type="button" class="close" data-dismiss="modal">
        <span aria-hidden="true">×</span>
        <span class="sr-only">Close</span>
    </button>
    <h4 class="modal-title">Create New Role</h4>
    <hr />

    <form role="form" class="form-horizontal" id="InputRoleForm">
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6">
                <div class="form-group form-group-xs">
                    <label class="col-xs-12 col-sm-3 col-md-4 control-label text-muted">Role Code</label>
                    <div class="col-xs-12 col-sm-9 col-md-8">
                        <input id="txtRoleCodeCreate" type="text" class="form-control" name="RoleCode" />
                    </div>
                </div>
                <div class="form-group form-group-xs">
                    <label class="col-xs-12 col-sm-3 col-md-4 control-label text-muted">Role Name</label>
                    <div class="col-xs-12 col-sm-9 col-md-8">
                        <input id="txtRoleNameCreate" type="text" class="form-control" name="RoleName" />
                    </div>
                </div>

            </div>


            <div class="col-xs-12 col-sm-6 col-md-6">
                <div class="form-group form-group-xs">
                    <label class="col-xs-12 col-sm-3 col-md-4 control-label text-muted">Application Code</label>
                    <div class="col-xs-12 col-sm-9 col-md-8">
                        <select class="form-control" id="ddlApplicationCode" name="ApplicationCode">
                            <option>E-Faktur</option>
                        </select>
                    </div>
                </div>


            </div>

        </div>

        <div class="row">

            <div class="col-xs-12 text-right">
                <div class="btn-group-sm">
                    <button type="submit" class="btn btn-primary" id="btnSave">Save</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal" id="btnCancel">Cancel</button>
                    @*<button type="button" class="btn btn-primary">Save</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>*@
                </div>
            </div>
        </div>
    </form>
</div>

<script type="text/javascript">
    
    $(document).ready(function () {
        $('#InputRoleForm').bootstrapValidator({
            live: 'enabled',
            fields: {
                RoleCode: {
                    validators: {
                        notEmpty: {
                            message: 'Role Code is required and can\'t be empty'
                        }
                    }
                },
                RoleName: {
                    validators: {
                        notEmpty: {
                            message: 'Role Name is required and can\'t be empty'
                        }
                    }
                },
                ApplicationCode: {
                    validators: {
                        notEmpty: {
                            message: 'Application Code is required and can\'t be empty'
                        }
                    }
                }
        
            }
        })
        .on('success.form.bv', function (e) {
            // Prevent form submission
            e.preventDefault();

            onSubmit();
        });
    });



    //Ajax POST/GET Method

function onSubmit() {
    Role = {
        RoleCode: $("#txtRoleCodeCreate").val(),
        RoleName: $("#txtRoleNameCreate").val(),
        ApplicationCode: $("#ddlApplicationCode").val()
    };
    $.ajax({
        type: "POST",
        url: URLSave,
        data: {
            data: JSON.stringify(Role)
            },
        beforeSend: function () {
            $('#btnSave').button('loading');
            if (DEBUG) {
                console.log('Save Start');
            }
        },
        success: function (result) {
            if (result.ResultCode) {
                msgOk(result.ResultDesc);
                onGet(1);
                $('#btnCancel').click();
            }
            else {
                msgError(result.ResultDesc);
            }
            if (DEBUG) {
                console.log('Save Success');
            }
        },
        error: function (XMLHttpRequest, textStatus, errorThrown) {
            if (DEBUG) {
                console.log("error: " + errorThrown);
            }
            msgError("An error has occured");
        },
        complete: function () {
            $('#btnSave').button('reset');
            if (DEBUG) {
                console.log('Save Done');
            }
        }
    });
}
</script>

TAM.EFaktur.Web/Views/Master_Role/_SearchCriteria.cshtml
<form role="form" class="form-horizontal" id="searchForm">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6 _searchCriteria">
            <div class="form-group form-group-xs">
                <label class="col-xs-12 col-sm-3 col-md-4 control-label text-muted">Role Code</label>
                <div class="col-xs-12 col-sm-9 col-md-8">
                    <div class="input-group input-group input-group-xs">
                        <input id="txtRoleCode" type="text" class="form-control" readonly />
                        <input id="lookupRoleCode" type="hidden" />
                        <span class="input-group-btn">
                            <a class="btn btn-primary modal-link" href="@Url.Action("PopupMultipleSearch", "Master_Role", new { Id = "lookupRoleCode" })"><i class="fa fa-search"></i></a>
                        </span>
                    </div>
                </div>
            </div>
            <div class="form-group form-group-xs _searchCriteria">
                <label class="col-xs-12 col-sm-3 col-md-4 control-label text-muted">Role Name</label>
                <div class="col-xs-12 col-sm-9 col-md-8">
                    <div class="input-group input-group input-group-xs">
                        <input id="txtRoleName" type="text" class="form-control" readonly />
                        <input id="lookupRoleName" type="hidden" />
                        <span class="input-group-btn">
                            <a class="btn btn-primary modal-link" href="@Url.Action("PopupMultipleSearch", "Master_Role", new { Id = "lookupRoleName" })"><i class="fa fa-search"></i></a>
                        </span>
                    </div>

                </div>
            </div>

        </div>


        <div class="col-xs-12 col-sm-6 col-md-6 _searchCriteria">

            <div class="form-group form-group-xs _searchCriteria">
                <label class="col-xs-12 col-sm-3 col-md-4 control-label text-muted">Application Code</label>
                <div class="col-xs-12 col-sm-9 col-md-8">
                    <select class="form-control">
                        <option value="E-Faktur">E-Faktur</option>
                    </select>
                </div>
            </div>

        </div>

    </div>

    <div class="row">
        <div class="col-xs-6" style="margin-top: 5px;">
          
        </div>
        <div class="col-xs-6 text-right">
            <div class="btn-group-sm">
                @Html.ActionLink("New Role", "PopupCreateRole", "Master_Role", null, new { @class = "modal-link btn btn-danger" })
                <button type="button" class="btn btn-primary" id="btnSearch" data-loading-text="&lt;i class='fa fa-refresh fa-spin'&gt;&lt;/i&gt; Loading...">Search</button>
                <button type="reset" class="btn btn-default" id="btnClearSearch" onclick="clearSearch()">Clear</button>
            </div>
        </div>
    </div>

</form>

<script type="text/javascript">

    //Clear Form Search
    function clearSearch() {
        document.getElementById("txtRoleCode").value = "";
        document.getElementById("lookupRoleCode").value = "";
        document.getElementById("txtRoleName").value = "";
        document.getElementById("lookupRoleName").value = "";
        }
</script>

TAM.EFaktur.Web/Views/Master_Role/_SimpleGrid.cshtml
@using TAM.EFaktur.Web.Models.Master_Role
@using TAM.EFaktur.Web.Models

@{
    List<MasterRoleDashboardViewModel> MasterRoleList = (List<MasterRoleDashboardViewModel>)ViewData["MasterRoleListDashboard"];
}


<div id="gridMasterRole">
    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <thead id="gridMasterRole">
                <tr>

                    <th style="width:70px;"></th>
                    <th onclick="sortItem(1)" style="cursor:pointer">Role Code</th>
                    <th onclick="sortItem(2)" style="cursor:pointer">Role Name</th>
                    <th onclick="sortItem(3)" style="cursor:pointer">Application Code</th>
                </tr>
            </thead>
            <tbody>
                @if (MasterRoleList != null && MasterRoleList.Count > 0)
                {
                    foreach (MasterRoleDashboardViewModel MasterRole in MasterRoleList)
                    {
                        <tr>
                            <td class="text-center">
                                <a href="@Url.Action("PopupUpdateRole", "Master_Role", new { Id = @MasterRole.Id })" class="modal-link btn btn-primary btn-xs btn-edit"><i class="fa fa-edit"></i></a>
                                <a href="@Url.Action("PopupDeleteRole", "Master_Role", new { Id = @MasterRole.Id })" class="modal-link btn btn-primary btn-xs btn-danger"><i class="fa fa-trash"></i></a>
                            </td>
                            <td>@MasterRole.RoleCode</td>
                            <td>@MasterRole.RoleName</td>
                            <td>@MasterRole.ApplicationCode</td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td class="danger" colspan="19"><b class="padding-5">No Record</b></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="row">
        <div class="col-xs-12 bottom-margin-20">
            @Html.Partial("_UIPaging")
        </div>
    </div>