TAM.EFaktur.Web/Models/Register/Register.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TAM.EFaktur.Web.Models.Register
{
    public class Register : BaseModel
    {
        public String SupplierNPWP { get; set; }
        public String RegistrationType { get; set; }
        public String RegistrationNum { get; set; }
        public String SKBType { get; set; }
        public DateTime RegistrationDate { get; set; }
        public String SupplierName { get; set; }
        public String SupplierAddress { get; set; }
        public String SupplierPhoneNum { get; set; }
        public String SupplierCountry { get; set; }
        public DateTime SupplierEstDate { get; set; }
        public DateTime ValidityPeriodFrom { get; set; }
        public DateTime ValidityPeriodTo { get; set; }
        public String CODSignerName { get; set; }
        public String CODSignerTitle { get; set; }
        public String UploadFile { get; set; }

        public dynamic MapFromModel(DateTime? EventDate = null, string EventActor = "")
        {
            dynamic args = new
            {
                Id = this.Id,
                SupplierNPWP = this.SupplierNPWP,
                RegistrationType = this.RegistrationType,
                RegistrationNum = this.RegistrationNum,
                SKBType = this.SKBType,
                RegistrationDate = this.RegistrationDate.FormatSQLDate(),
                SupplierName = this.SupplierName,
                SupplierAddress = this.SupplierAddress,
                SupplierPhoneNum = this.SupplierPhoneNum,
                SupplierCountry = this.SupplierCountry,
                SupplierEstDate = this.SupplierEstDate.FormatSQLDate(),
                ValidityPeriodFrom = this.ValidityPeriodFrom,
                ValidityPeriodTo = this.ValidityPeriodTo,
                CODSignerName = this.CODSignerName,
                CODSignerTitle = this.CODSignerTitle,
                UploadFile = this.UploadFile,
            };
            return args;
        }
    }
}

TAM.EFaktur.Web/Models/Register/RegisterApprovalStatusViewModel.cs
using System;

namespace TAM.EFaktur.Web.Models.Register
{
    public class RegisterApprovalStatusViewModel
    {
        public string TaxFacNo { get; set; }
        public string ApprovalStatus { get; set; }
        public Nullable<DateTime> ApprovalDate { get; set; }
        public DateTime RecordedDate { get; set; }
        public string RegistrationNo { get; set; }

        public dynamic MapFromModel(string EventActor)
        {
            return new
            {
                TaxFacNo = TaxFacNo,
                ApprovalStatus = ApprovalStatus,
                ApprovalDate = ApprovalDate,
                RecordedDate = RecordedDate,
                RecordedBy = EventActor,
                RegistrationNo = RegistrationNo
            };
        }
    }
}

TAM.EFaktur.Web/Models/Register/RegisterCreateUpdate.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TAM.EFaktur.Web.Models.Register
{
    public class RegisterCreateUpdate
    {
        public String TaxFacCategory { get; set; }
        public String TaxFacNo { get; set; }
        public String SKBType { get; set; }
        public String SKBTypeOthers { get; set; }
        public String TaxFacDate { get; set; }
        public String SupplierName { get; set; }
        public String SupplierNPWP { get; set; }
        public String SupplierAddress { get; set; }
        public String SupplierPhoneNo { get; set; }
        public String SupplierCountry { get; set; }
        public String SupplierEstDate { get; set; }
        public String FacValidPeriodFrom { get; set; }
        public String FacValidPeriodTo { get; set; }
        public String FacDocSignerName { get; set; }
        public String FacDocSignerTitle { get; set; }
        public String RecordedDate { get; set; }
        public String RecordedBy { get; set; }
        public String ApprovalStatus { get; set; }
        public String ApprovalDate { get; set; }
        public String UploadFile { get; set; }
        public String RegistrationNo { get; set; }
        public String MapCode { get; set; }
        public int Seq { get; set; }
        public String PDFFacStatus { get; set; }
    }
}

TAM.EFaktur.Web/Models/Register/RegisterDashboardViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TAM.EFaktur.Web.Models.Register
{
    public class RegisterDashboardViewModel : Controller
    {
        public Guid Id { get; set; }
        public int RowNum { get; set; }
        public DateTime RegistrationDate { get; set; }
        public string CODSignerName { get; set; }
        public string CODSignerTitle { get; set; }

        public string TaxFacCategory { get; set; }
        public string TaxFacNo { get; set; }
        public string SKBType { get; set; }
        public string SKBTypeOthers { get; set; }
        public DateTime TaxFacDate { get; set; }
        public string SupplierName { get; set; }
        public string SupplierNPWP { get; set; }
        public string SupplierAddress { get; set; }
        public string SupplierPhoneNo { get; set; }
        public string SupplierCountry { get; set; }
        public string SupplierCountryName { get; set; }
        public DateTime SupplierEstDate { get; set; }
        public DateTime FacValidPeriodFrom { get; set; }
        public DateTime FacValidPeriodTo { get; set; }
        public string FacDocSignerName { get; set; }
        public string FacDocSignerTitle { get; set; }
        public DateTime RecordedDate { get; set; }
        public string RecordedBy { get; set; }
        public string ApprovalStatus { get; set; }
        public DateTime ApprovalDate { get; set; }
        public string UploadFile { get; set; }
        public string RegistrationNumber { get; set; }
        public string PDFFacStatus { get; set; }
        public int Seq { get; set; }

        public string MAPCode { get; set; }
    }
}

TAM.EFaktur.Web/Models/Register/RegisterExcelViewModel.cs
using System;

namespace TAM.EFaktur.Web.Models.Register
{
    public class RegisterExcelViewModel
    {
        public string Field1 { get; set; }
        public string Field2 { get; set; }
        public string Field3 { get; set; }
        public string Field4 { get; set; }
        public string Field5 { get; set; }
        public string Field6 { get; set; }
        public string Field7 { get; set; }
        public string Field8 { get; set; }
        public string Field9 { get; set; }
        public string Field10 { get; set; }
        public string Field11 { get; set; }
        public string Field12 { get; set; }
        public string Field13 { get; set; }
        public string Field14 { get; set; }
        public string Field15 { get; set; }
        public string Field16 { get; set; }
        public string Field17 { get; set; }
        public string Field18 { get; set; }
        public string Field19 { get; set; }
        public string Field20 { get; set; }
        public string Field21 { get; set; }
        public string Field22 { get; set; }
        public string Field23 { get; set; }

    }
}

TAM.EFaktur.Web/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using TAM.EFaktur.Web.Models;
using TAM.EFaktur.Web.Models.Master_Config;
using TAM.EFaktur.Web.Models.Register;
using Toyota.Common.Web.Platform;

namespace TAM.EFaktur.Web.Controllers
{
    public class RegisterController : BaseController
    {
        bool isFullAccess { get; set; }

        protected override void Startup()
        {
            Settings.Title = "Dashboard Register Tax Facility";

            int countArr = CurrentLogin.Roles.Count();

            List<string> RoleId = new List<string>();

            for (int i = 0; i < countArr; i++)
            {
                RoleId.Add(CurrentLogin.Roles[i].Id);
            }

            Config config = MasterConfigRepository.Instance.GetByConfigKey("FacilityDataFullAccessRole");//new by role


            string[] RegisterFullAccessRole = { "" };
            string[] RoleIds = RoleId.ToArray();

            if (config != null)
            {
                RegisterFullAccessRole = config.ConfigValue.Split(';');
                foreach (var item in RoleIds)
                {
                    if (RegisterFullAccessRole.Contains(item))
                    {
                        isFullAccess = true;
                    }
                }
            }
            ViewBag.IsFullAccess = isFullAccess;
        }
        
        public ActionResult PopupCreateEbupot()
        {
            return PartialView("_PopupCreateEbupot");
        }

        #region PopUp
        public ActionResult PopupUploadRegisterFile(string taxFaxNo)
        {
            //Config config = MasterConfigRepository.Instance.GetByConfigKey("UrlTemplateUploadWHT");
            //ViewBag.TemplateLink = config != null ? config.ConfigValue : "#";
            ViewBag.TaxFacNo = taxFaxNo;
            return PartialView("_PopupUploadRegisterFile");
        }

        public ActionResult PopupMultipleSearch(string Id)
        {
            ViewBag.ElementId = Id;
            return PartialView("_PopupMultipleSearch");
        }

        public ActionResult PopupTextAreaSearch(string Id)
        {
            ViewBag.ElementId = Id;
            return PartialView("_PopupTextAreaSearch");
        }

        public ActionResult PopupUploadApprovalStatus()
        {
            Config config = MasterConfigRepository.Instance.GetByConfigKey("UrlTemplateApprovalStatusTaxFacility");
            ViewBag.TemplateLink = config != null ? config.ConfigValue : "#";
            return PartialView("_PopupUploadApprovalStatus");
        }

        public ActionResult PopupUploadTaxFacilityDataFile()
        {
            Config config = MasterConfigRepository.Instance.GetByConfigKey("UrlTemplateTaxFacilityFile");
            ViewBag.TemplateLink = config != null ? config.ConfigValue : "#";
            return PartialView("_PopupUploadTaxfacilityDataFile");
        }
        #endregion

        [HttpPost]
        public ActionResult GetRegisterList(FormCollection collection, int sortBy, bool sortDirection, int page, int size)
        {
            #region cek isFullAccess
            int countArr = CurrentLogin.Roles.Count();

            List<string> RoleId = new List<string>();

            for (int i = 0; i < countArr; i++)
            {
                RoleId.Add(CurrentLogin.Roles[i].Id);
            }

            Config config = MasterConfigRepository.Instance.GetByConfigKey("FacilityDataFullAccessRole"); //new by role

            string[] RegisterFullAccessRole = { "" };
            string[] RoleIds = RoleId.ToArray();

            //if (config != null)
            //{
            //    RegisterFullAccessRole = config.ConfigValue.Split(';');
            //    foreach (var item in RoleIds)
            //    {
            //        if (RegisterFullAccessRole.Contains(item))//abc;acc;abb
            //        {
            //            isFullAccess = true;
            //            break;
            //        }
            //    }

            //}
            #endregion
            isFullAccess = true;
            var data = collection["data"];
            var model = new RegisterDashboardSearchParamViewModel();

            if (!string.IsNullOrEmpty(data))
                model = new JavaScriptSerializer().Deserialize<RegisterDashboardSearchParamViewModel>(data);

            Paging pg = new Paging
            (
                RegisterRepository.Instance.Count(model, CurrentHRIS.DivisionName, CurrentLogin.Username, isFullAccess),
                page,
                size
            );
            ViewData["Paging"] = pg;
            ViewData["RegisterListDashboard"] = RegisterRepository.Instance.GetList(model, CurrentHRIS.DivisionName, CurrentLogin.Username, sortBy, sortDirection ? "ASC" : "DESC", pg.StartData, pg.EndData, isFullAccess);

            return PartialView("_SimpleGrid");
        }

        public JsonResult DeleteRegister(FormCollection collection, bool checkAll)
        {
            #region Cek Register Full Access Role
            int countArr = CurrentLogin.Roles.Count();

            List<string> RoleId = new List<string>();

            for (int i = 0; i < countArr; i++)
            {
                RoleId.Add(CurrentLogin.Roles[i].Id);
            }

            Config config = MasterConfigRepository.Instance.GetByConfigKey("WHTFullAccessRole");//new by role

            string[] RegisterFullAccessRole = { "" };
            string[] RoleIds = RoleId.ToArray();

            if (config != null)
            {
                RegisterFullAccessRole = config.ConfigValue.Split(';');
                foreach (var item in RoleIds)
                {
                    if (RegisterFullAccessRole.Contains(item))
                    {
                        isFullAccess = true;
                    }
                }
            }
            #endregion

            Result result = new Result
            {
                ResultCode = true,
                ResultDesc = "Delete successfully"
            };

            try
            {
                var searchParam = collection["data"];
                var taxFacNoList = collection["taxFacNoList"];
                var taxFacSeqList = collection["taxFacSeqList"];
                var searchParamModel = new RegisterDashboardSearchParamViewModel();
                List<string> TaxFacNoList = new List<string>();
                List<string> TaxFacSeqList = new List<string>();
                if (!string.IsNullOrEmpty(searchParam) && checkAll)
                {
                    searchParamModel = new JavaScriptSerializer().Deserialize<RegisterDashboardSearchParamViewModel>(searchParam);
                    TaxFacNoList = RegisterRepository.Instance.GetTaxFacilityByNo(searchParamModel, CurrentHRIS.DivisionName, CurrentLogin.Username, isFullAccess).Select(a=>a.TaxFacNo).ToList();
                }
                else
                {
                    TaxFacNoList = new JavaScriptSerializer().Deserialize<List<string>>(taxFacNoList);
                    TaxFacSeqList = new JavaScriptSerializer().Deserialize<List<string>>(taxFacSeqList);
                }

                List<string[]> ListArr = new List<string[]>();

                result = RegisterRepository.Instance.DeleteRegisterById(TaxFacNoList, TaxFacSeqList, CurrentLogin.Username);

                return Json(result.AsDynamic(), JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                result.ResultCode = false;
                result.ResultDesc = e.LogToApp("Register Delete", MessageType.ERR, CurrentLogin.Username).Message;
                return Json(result.AsDynamic(), JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult GenerateDownloadFile(FormCollection collection, string type, bool checkAll)
        {
            #region Cek Register Full Access Role
            int countArr = CurrentLogin.Roles.Count();

            List<string> RoleId = new List<string>();

            for (int i = 0; i < countArr; i++)
            {
                RoleId.Add(CurrentLogin.Roles[i].Id);
            }

            Config config = MasterConfigRepository.Instance.GetByConfigKey("FacilityDataFullAccessRole");//new by role


            string[] RegisterFullAccessRole = { "" };
            string[] RoleIds = RoleId.ToArray();

            //if (config != null)
            //{
            //    RegisterFullAccessRole = config.ConfigValue.Split(';');
            //    foreach (var item in RoleIds)
            //    {
            //        if (RegisterFullAccessRole.Contains(item))
            //        {
            //            isFullAccess = true;
            //        }
            //    }
            //}
            #endregion
            isFullAccess = true;
            Result result = new Result
            {
                ResultCode = true,
                ResultDesc = "File for download generated successfully"
            };

            string fullPath = string.Empty;
            int totalDataCount = 0;
            int totalDataFailed = 0;
            try
            {
                var searchParam = collection["data"];
                var taxFacNoList = collection["taxFacNoList"];
                var searchParamModel = new RegisterDashboardSearchParamViewModel();
                List<string> TaxFacNoList = new List<string>();
                if (!string.IsNullOrEmpty(searchParam) && checkAll)
                {
                    searchParamModel = new JavaScriptSerializer().Deserialize<RegisterDashboardSearchParamViewModel>(searchParam);
                    TaxFacNoList = RegisterRepository.Instance.GetTaxFacilityByNo(searchParamModel, CurrentHRIS.DivisionName, CurrentLogin.Username, isFullAccess).Select(a => a.TaxFacNo).ToList();
                }
                else
                {

TAM.EFaktur.Web/Views/Register/Register.cshtml
@{
    ViewBag.Title = "RegisterTextFacilityDashboard";
}

@section HeadScript{
    <style>
        ._searchCriteria {
            display: none;
        }
    </style>
}

@Html.Partial("_SearchCriteria")

<div class="_line-br"></div>


<div class="row">
    <div class="col-xs-12 col-sm-6">
        @Html.Partial("_UIPageSize")
    </div>
    <div class="col-xs-12 col-sm-6 text-right">
        <div class="form-group form-group-xs">
            @Html.Partial("_UITotalSelectedIndicator")

            *@if (Html.Toyota().Authorization.IsAuthorizedToAccessFeature("RegisterFacility", "PrintFacilityPDF"))
            {
                <button id="btnPrint" type="button" class="btn btn-primary btn-sm">Print Facility PDF</button>
            }
            @*@if ( Html.Toyota().Authorization.IsAuthorizedToAccessFeature("RegisterFacility", "Delete") || Html.Toyota().Authorization.IsAuthorizedToAccessFeature("RegisterFacility", "DeleteDraft"))
            {*@
                <div class="btn-group btn-group-sm">
                    <button type="button" class="btn btn-warning" id="btnAction" data-loading-text="&lt;i class='fa fa-refresh fa-spin'&gt;&lt;/i&gt; Loading...">Action</button>
                    <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown">
                        <span class="caret"></span>
                        <span class="sr-only">Toggle Dropdown</span>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-right" role="menu">
        
                        @if (Html.Toyota().Authorization.IsAuthorizedToAccessFeature("RegisterFacility", "DeleteTaxFacility"))
                        {
                        <li><a style="cursor:pointer" onclick="Delete()">Delete Tax Facility</a></li>
                        }
                    </ul>
                </div>
            @*}*@
            @if (Html.Toyota().Authorization.IsAuthorizedToAccessFeature("RegisterFacility", "DownloadPDF") ||
                 Html.Toyota().Authorization.IsAuthorizedToAccessFeature("RegisterFacility", "DownloadReport"))
            {
                <div class="btn-group btn-group-sm">
                    <button id="btnDownloadChoice" type="button" class="btn btn-primary" data-loading-text="&lt;i class='fa fa-refresh fa-spin'&gt;&lt;/i&gt; Loading...">Download</button>
                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                        <span class="caret"></span>
                        <span class="sr-only">Toggle Dropdown</span>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-right" role="menu">
                        @if (Html.Toyota().Authorization.IsAuthorizedToAccessFeature("RegisterFacility", "DownloadReport"))
                        {
                            <li><a href="#" onclick="Download('xlsreport')">Download Report</a></li>
                        }
                        @if (Html.Toyota().Authorization.IsAuthorizedToAccessFeature("RegisterFacility", "DownloadPDF"))
                        {
                            <li><a href="#" onclick="Download('pdf')">Download File Doc. PDF</a></li>
                        }
                    </ul>
                </div>
            }

            @if (Html.Toyota().Authorization.IsAuthorizedToAccessFeature("RegisterFacility", "UploadApprovalStatus") ||
                 Html.Toyota().Authorization.IsAuthorizedToAccessFeature("RegisterFacility", "UploadTaxFacilityData"))
            {
                <div class="btn-group btn-group-sm">
                    <button type="button" class="btn btn-warning">Upload</button>
                    <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown">
                        <span class="caret"></span>
                        <span class="sr-only">Toggle Dropdown</span>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-right" role="menu">
                        @if (Html.Toyota().Authorization.IsAuthorizedToAccessFeature("RegisterFacility", "UploadApprovalStatus"))
                        {
                            <li>@Html.ActionLink("Upload Approval Status", "PopupUploadApprovalStatus", "Register", null, new { @class = "modal-link" })</li>
                        }
                        
                        @*@if (Html.Toyota().Authorization.IsAuthorizedToAccessFeature("RegisterFacility", "UploadTaxFacilityData"))
                        {
                            <li>@Html.ActionLink("Upload Tax Facility Data", "PopupUploadTaxFacilityDataFile", "Register", null, new { @class = "modal-link" })</li>
                        }*@
                    </ul>
                </div>
            }
        </div>
    </div>
</div>

<div id="gridRegister">
    @Html.Partial("_SimpleGrid")
</div>
@section BodyScript{
    <script type="text/javascript">
        $(document).ready(function () {
            /* toggle show or hide searching criteria (that has class _searchCriteria) */
            $("#lnsearch-toggle").click(function () {
                var _criteria = $("._searchCriteria");
                _criteria.toggle(200, "linear");

                var text = $("#lnsearch-toggle").text();
                $("#lnsearch-toggle").text(text == "Expand search criteria" ? "Less search criteria" : "Expand search criteria");
            });
        });
    </script>
}

@Html.Partial("_Javascript")

TAM.EFaktur.Web/Views/Register/_PopupCreateEbupot.cshtml
@{
    ViewBag.Title = "_PopupCreateEbupot";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>_PopupCreateEbupot</h2>

TAM.EFaktur.Web/Views/Register/_SimpleGrid.cshtml
@using TAM.EFaktur.Web.Models.Register
@using TAM.EFaktur.Web.Models

@{
    List<RegisterDashboardViewModel> RegisterList = (List<RegisterDashboardViewModel>)ViewData["RegisterListDashboard"];
}

<div class="table-responsive _table-flow">
    <table class="table table-striped table-bordered table-condensed fixed-columns" id="DashboardRegister" style="width: auto !important;">
        <thead>
            <tr>
                <th class="fixed-column _col-checkbox" width="35px;"><input type="checkbox" id="checkall" onclick="checkAll()" /></th>
                <th class="fixed-column _col" onclick="sortItem(1)" style="cursor:pointer">Tax Facility Category &nbsp;&nbsp;&nbsp;<i class="fa fa-sort"></i></th>
                <th class="fixed-column _col" onclick="sortItem(2)" style="cursor:pointer">SKB Type &nbsp;&nbsp;&nbsp;<i class="fa fa-sort"></i></th>
                <th class="fixed-column _col" onclick="sortItem(3)" style="cursor:pointer">Tax Facility No. &nbsp;&nbsp;&nbsp;<i class="fa fa-sort"></i></th>
                <th onclick="sortItem(4)" style="cursor:pointer">Tax Facility Date &nbsp;&nbsp;&nbsp;<i class="fa fa-sort"></i></th>
                <th onclick="sortItem(5)" style="cursor:pointer">Supplier Name &nbsp;&nbsp;&nbsp;<i class="fa fa-sort"></i></th>
                <th onclick="sortItem(6)" style="cursor:pointer">Supplier NPWP/TIN &nbsp;&nbsp;&nbsp;<i class="fa fa-sort"></i></th>
                <th onclick="sortItem(7)" style="cursor:pointer">Supplier Phone No. &nbsp;&nbsp;&nbsp;<i class="fa fa-sort"></i></th>
                <th onclick="sortItem(8)" style="cursor:pointer">Supplier Country &nbsp;&nbsp;&nbsp;<i class="fa fa-sort"></i></th>
                <th onclick="sortItem(9)" style="cursor:pointer">Supplier Country Code &nbsp;&nbsp;&nbsp;<i class="fa fa-sort"></i></th>
                <th onclick="sortItem(10)" style="cursor:pointer">Supplier Establishment Date &nbsp;&nbsp;&nbsp;<i class="fa fa-sort"></i></th>
                <th onclick="sortItem(11)" style="cursor:pointer">Facility Valid Period From&nbsp;&nbsp;&nbsp;<i class="fa fa-sort"></i></th>
                <th onclick="sortItem(12)" style="cursor:pointer">Facility Valid Period To&nbsp;&nbsp;&nbsp;<i class="fa fa-sort"></i></th>
                <th onclick="sortItem(13)" style="cursor:pointer">Facility Doc. Signer Name &nbsp;&nbsp;&nbsp;<i class="fa fa-sort"></i></th>
                <th onclick="sortItem(14)" style="cursor:pointer">Facility Doc. Signer Tittle &nbsp;&nbsp;&nbsp;<i class="fa fa-sort"></i></th>
                <th onclick="sortItem(22)" style="cursor:pointer">MAP Code &nbsp;&nbsp;&nbsp;<i class="fa fa-sort"></i></th>
                <th onclick="sortItem(15)" style="cursor:pointer">Recorded Date &nbsp;&nbsp;&nbsp;<i class="fa fa-sort"></i></th>

                <th onclick="sortItem(23)" style="cursor:pointer">Recorded Time &nbsp;&nbsp;&nbsp;<i class="fa fa-sort"></i></th>

                <th onclick="sortItem(16)" style="cursor:pointer">Recorded By &nbsp;&nbsp;&nbsp;<i class="fa fa-sort"></i></th>
                <th onclick="sortItem(17)" style="cursor:pointer">Approval Status &nbsp;&nbsp;&nbsp;<i class="fa fa-sort"></i></th>
                <th onclick="sortItem(18)" style="cursor:pointer">Approval Date &nbsp;&nbsp;&nbsp;<i class="fa fa-sort"></i></th>
                <th onclick="sortItem(19)" style="cursor:pointer">Registration Number &nbsp;&nbsp;&nbsp;<i class="fa fa-sort"></i></th>
                <th onclick="sortItem(20)" style="cursor:pointer">PDF Facility Status &nbsp;&nbsp;&nbsp;<i class="fa fa-sort"></i></th>
                <th onclick="sortItem(21)" style="cursor:pointer">Upload Doc. &nbsp;&nbsp;&nbsp;<i class="fa fa-sort"></i></th>
                @*<th onclick="sortItem(21)" style="cursor:pointer">Seq &nbsp;&nbsp;&nbsp;<i class="fa fa-sort"></i></th>*@

            </tr>
        </thead>
        <tbody>
            @if (RegisterList != null && RegisterList.Count > 0)
            {
                foreach (RegisterDashboardViewModel Register in RegisterList)
                {
            <tr>
                <td class="text-center fixed-column">
                    <input id="@string.Format("chkGrid{0}", Register.RowNum)" type="checkbox" class="check" onchange="javascript:checkGrid(this.id)" />
                    <input type="hidden" class="TaxFacNo" value="@Register.TaxFacNo" />
                    <input type="hidden" class="TaxFacSeq" value="@Register.Seq" />
                </td>
                <td class="fixed-column">@Register.TaxFacCategory</td>
                <td class="fixed-column">@Register.SKBType</td>
                <td class="fixed-column">@Register.TaxFacNo</td>
                <td>@Register.TaxFacDate.FormatViewDate()</td>
                @*<td class="fixed-column WHtStatusInvoice">@Register.TaxFacDate.FormatViewDate()</td>*@
                <td>@Register.SupplierName</td>
                <td>@Register.SupplierNPWP</td>
                <td>@Register.SupplierPhoneNo</td>
                <td>@Register.SupplierCountryName</td>
                <td>@Register.SupplierCountry</td>
                <td>@Register.SupplierEstDate.FormatViewDate()</td>
                <td>@Register.FacValidPeriodFrom.FormatViewDate()</td>
                <td>@Register.FacValidPeriodTo.FormatViewDate()</td>
                <td>@Register.FacDocSignerName</td>
                <td>@Register.FacDocSignerTitle</td>
                <td>@Register.MAPCode</td>
                <td>@Register.RecordedDate.FormatViewDate()</td>
                <td>@Register.RecordedDate.FormatViewTime()</td>
                @*@if (Register.RecordedDate != DateTime.MinValue) //!dat.HasValue apabila datetimenullable
        {
            @Register.RecordedDate.FormatViewTime()
        }*@
                <td>@Register.RecordedBy</td>
                <td>@Register.ApprovalStatus</td>
                <td>@Register.ApprovalDate.FormatViewDate()</td>
                <td>@Register.RegistrationNumber</td>
                <td>
                    @if (Register.PDFFacStatus == "0" || Register.PDFFacStatus == null)
                    {
                        <text>
                            Not Exist
                        </text>
                    }
                    else
                    {
                        <text>
                            Exist
                        </text>
                    }
                </td>

                <td>

            @if (Register.PDFFacStatus == "0" || Register.PDFFacStatus == null)
        {
            @Html.ActionLink("Upload File", "PopupUploadRegisterFile", "Register", new { taxFaxNo = Register.TaxFacNo } ,new { @class = "modal-link" })
        }
        </td>
                @*<td style="display:none">@Register.Seq</td>*@
        

            </tr>
                }
            }
            else
            {
                <tr>
                    <td class="danger" colspan="31"><b class="padding-5">No Record</b></td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div class="row">
    <div class="col-xs-12 bottom-margin-20">
        @Html.Partial("_UIPaging")
    </div>
</div>
<script>
    function DownloadFilePDF(url) {
        alert(url);
        window.location = "@Html.Toyota().Page.GetActionUrl("DownloadTemp")";
    }
</script>
<script>
    function pageurl(url) {
        window.Location = url;
    };
</script>